apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quick-mkdocs.fullname" . }}-mkdoc-conf
  labels:
    {{- include "quick-mkdocs.labels" . | nindent 4 }}
data:
  mkdocs.yml: |
    {{- toYaml .Values.mkdocConfig | nindent 4 }}